# Generated by Django 4.0.3 on 2022-04-02 19:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_user_background_img_url_alter_follower_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='background_img_url',
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
    ]
