# Generated by Django 4.0.3 on 2022-04-02 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
    ]
